---
title: "Documentation"
author: "PC"
date: "January 24, 2015"
output: html_document
---
Galton's height data for parents and children

Description

Data set from tabulated data set used by Galton in 1885 to study the relationship between a parent's height and their childrens.

Usage

data(galton)
Format

A data frame with 928 observations on the following 2 variables.

child
The child's height
parent
The “midparent” height
Details

The midparent's height is an average of the fathers height and 1.08 times the mother's. In the data there are 205 different parents and 928 children. The data here is truncated at the ends for both parents and children so that it can be treated as numeric data. The data were tabulated and consequently made discrete. The father.son data set is similar data used by Galton and is continuous.

This shiny app helps us predict the expected childs height with every inch change in the parent height.

Source

This data was found at http://www.bun.kyoto-u.ac.jp/~suchii/galton86.html.

See also the data.set father.son which was found from http://stat-www.berkeley.edu/users/juliab/141C/pearson.dat.
